services:
  - type: web
    name: ecommerce-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5000
  - type: static
    name: ecommerce-web-frontend
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: dist

